server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: ${DEV_DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity-service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DEV_DBMS_USERNAME:root}
    password: ${DEV_DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${DEV_SIGNERKEY:f7fc18c45476e0082feea9258bfeb787949bed58d8e00a39df56c13ac0cf57d6}
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second